# Generated by Django 4.0.5 on 2022-06-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=168)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('street_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('address_building', models.CharField(max_length=10)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('shop_street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.street')),
            ],
        ),
    ]
